server:
  port: ${PORT:5000}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql-sgp1-00678-do-user-11389822-0.b.db.ondigitalocean.com:25060/r2s
    username: doadmin
    password: AVNS_Bakc6GfajCO0oMR
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        id:
          new_generator_mappings: true
        show:
          sql: true
        format_sql: true
        hb2dll:
          auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  main:
    allow-circular-references: true
cloud:
  aws:
    credentials:
      access-key: AKIAXCJ5SNGBQJR2NKBE
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: phuonganh-storage
springdoc:
  api-docs:
    path: /swagger/api-docs
    enabled: true
  swagger-ui:
    path: /swagger/swagger-ui-custom.html
    operations-sorter: desc







